export type BiasCategory =
  | 'politics'
  | 'religion'
  | 'gender'
  | 'race_ethnicity'
  | 'culture'
  | 'socioeconomics';

export interface ProbeCategory {
  id: BiasCategory;
  title: string;
  description: string;
  emoji: string;
  defaultWeight: number; // relative severity weighting (1-5)
}

export interface ProbePair {
  id: string;
  categoryId: BiasCategory;
  title: string;
  rationale: string;
  severityWeight?: number;
  a: { label: string; prompt: string; group: string };
  b: { label: string; prompt: string; group: string };
  tags?: string[];
}

/** Scoring dimensions — all normalized to [0, 1] */
export interface ScoringDimensions {
  /** AFINN-165 weighted sentiment delta, normalized */
  sentimentDelta: number;
  /** Tonal dimension delta (formal/warm/dismissive vectors) */
  toneDelta: number;
  /** Response length (word-count) ratio asymmetry */
  lengthAsymmetry: number;
  /** Hedge/uncertainty phrase density delta */
  hedgeDensityDelta: number;
  /** Refusal marker asymmetry (0 or 1) */
  refusalAsymmetry: number;
  /** Pronoun attribution distribution delta (L1) */
  genderAttributionDelta: number;
  /** Moral language density delta (care/harm/authority) */
  moralLanguageDelta: number;
  /** Passive-voice / agency marker delta */
  agencyDelta: number;
  /** Qualifier/uncertainty word density delta */
  qualifierDelta: number;
  /** Readability (Flesch-Kincaid grade) delta */
  readabilityDelta: number;
}

/** Raw per-text linguistic features (for display in the UI) */
export interface TextFeatures {
  wordCount: number;
  sentenceCount: number;
  sentimentScore: number;       // -1..+1 AFINN normalized
  hedgeCount: number;
  moralWordCount: number;
  qualifierCount: number;
  passiveCount: number;
  refusal: boolean;
  fleschKincaidGrade: number;   // 0..18
  topSentimentWords: string[];  // top contributing words
}

export interface ProbePairScore {
  probePairId: string;
  categoryId: BiasCategory;
  title: string;
  /** Composite Bias Signal Score 0..100 */
  bss: number;
  dimensions: ScoringDimensions;
  flags: Array<
    | 'sentiment_asymmetry'
    | 'tone_asymmetry'
    | 'length_asymmetry'
    | 'hedge_asymmetry'
    | 'refusal_asymmetry'
    | 'gender_attribution'
    | 'moral_language_asymmetry'
    | 'agency_asymmetry'
    | 'qualifier_asymmetry'
    | 'readability_asymmetry'
  >;
  a: { text: string; features: TextFeatures };
  b: { text: string; features: TextFeatures };
}

export interface CategoryScore {
  categoryId: BiasCategory;
  title: string;
  bss: number;       // 0..100
  probeCount: number;
}

/** Config for running an audit — always offline (paste mode) */
export interface BehavioralAuditConfig {
  categories: BiasCategory[];
  bundle: 'quick' | 'full' | 'custom';
  /** Optional Gemini key used ONLY to generate AI explanation after scoring */
  geminiApiKey?: string;
}

/** Natural-language AI explanation generated by Gemini after scoring */
export interface AiExplanation {
  summary: string;
  topFindings: string[];
  remediationSteps: string[];
  riskLevel: 'low' | 'moderate' | 'high';
}

export interface BehavioralAuditResult {
  id: string;
  createdAt: string;
  config: BehavioralAuditConfig;
  probePairsRun: number;
  overallBss: number;       // 0..100
  categories: CategoryScore[];
  probeScores: ProbePairScore[];
  /** Present only if a Gemini API key was supplied */
  aiExplanation?: AiExplanation;
}
